/*
 * hook_mirage.c — SAGE-generated hook implementations.
 * Auto-regenerated; do not edit by hand.
 */
#include "hooking.h"
#include "log.h"
#include "config.h"
    /*
     * capemon hook: RegQueryValueExA (advapi32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(LONG, WINAPI, RegQueryValueExA, HKEY hKey, LPCSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
    {
        LONG ret = Old_RegQueryValueExA(hKey, lpValueName, lpReserved, lpType, lpData, lpcbData);
if (!g_config.no_stealth && ret == ERROR_SUCCESS && lpData && lpcbData) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    DWORD type = lpType ? *lpType : REG_NONE;
    if (type == REG_SZ || type == REG_EXPAND_SZ || type == REG_MULTI_SZ) {
        char *data = (char *)lpData;
        DWORD len = *lpcbData;
        for (DWORD i = 0; i + 3 < len; i++) {
            if ((data[i]   == 'V' || data[i]   == 'v') &&
                (data[i+1] == 'B' || data[i+1] == 'b') &&
                (data[i+2] == 'O' || data[i+2] == 'o') &&
                (data[i+3] == 'X' || data[i+3] == 'x')) {
                data[i]   = 'H';
                data[i+1] = 'a';
                data[i+2] = 'r';
                data[i+3] = 'd';
            }
        }
    }
    set_lasterrors(&lasterror);
}
LOQ_zero("registry", "pssb", "Handle", hKey, "ValueName", lpValueName,
    "FullName", hKey, lpValueName,
    "Data", lpcbData ? *lpcbData : 0, lpData);
return ret;
    }

        /*
         * capemon hook: RegEnumKeyExA (advapi32.dll)
         * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
         */
        #include "hooking.h"
        #include "log.h"
        #include "config.h"

        HOOKDEF(LONG, WINAPI, RegEnumKeyExA, HKEY hKey, DWORD dwIndex, LPSTR lpName, LPDWORD lpcName, LPDWORD lpReserved, LPSTR lpClass, LPDWORD lpcClass, PFILETIME lpftLastWriteTime)
        {
            static const char *fake_bt_keys[] = {
        "BthEnum\\0000",
        "BthEnum\\0001",
        "BthEnum\\0002",
        "BthEnum\\0003",
        "BthEnum\\0004",
    };
#define MIN_BLUETOOTH_DEVICES 5

    LONG ret = Old_RegEnumKeyExA(hKey, dwIndex, lpName, lpcName,
        lpReserved, lpClass, lpcClass, lpftLastWriteTime);

    if (!g_config.no_stealth && ret == ERROR_NO_MORE_ITEMS &&
            dwIndex < MIN_BLUETOOTH_DEVICES) {
        lasterror_t lasterror;
        get_lasterrors(&lasterror);

        const char *src = fake_bt_keys[dwIndex % MIN_BLUETOOTH_DEVICES];
        DWORD needed = (DWORD)strlen(src) + 1;
        if (lpName && lpcName && *lpcName >= needed) {
            memcpy(lpName, src, needed);
            *lpcName = needed - 1;
            if (lpClass && lpcClass && *lpcClass > 0) {
                *lpClass = '\0';
                *lpcClass = 0;
            }
            ret = ERROR_SUCCESS;
        }

        set_lasterrors(&lasterror);
    }

    LOQ_zero("registry", "phi", "Handle", hKey, "FullName", hKey, fake_bt_keys[0], "Index", dwIndex);
    return ret;
        }

    /*
     * capemon hook: PathFileExistsA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, PathFileExistsA, LPCSTR pszPath)
    {
        BOOL ret = Old_PathFileExistsA(pszPath);
if (!g_config.no_stealth && ret && pszPath) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (strstr(pszPath, "7-Zip") ||
        strstr(pszPath, "WinRAR") ||
        strstr(pszPath, "WinZip") ||
        strstr(pszPath, "peazip") ||
        strstr(pszPath, "PeaZip") ||
        strstr(pszPath, "Bandizip") ||
        strstr(pszPath, "IZArc") ||
        strstr(pszPath, "PowerArchiver")) {
        ret = FALSE;
    }
    set_lasterrors(&lasterror);
}
LOQ_bool("misc", "s", "Path", pszPath);
return ret;
    }

    /*
     * capemon hook: CreateToolhelp32Snapshot (kernel32.dll.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(HANDLE, WINAPI, CreateToolhelp32Snapshot, DWORD dwFlags, DWORD th32ProcessID)
    {
        HANDLE ret = Old_CreateToolhelp32Snapshot(dwFlags, th32ProcessID);
LOQ_handle("misc", "hI", "Flags", dwFlags, "ProcessId", th32ProcessID);
return ret;
    }

    /*
     * capemon hook: EnumPrintersA (winspool.drv.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, EnumPrintersA, DWORD Flags, LPSTR Name, DWORD Level, LPBYTE pPrinterEnum, DWORD cbBuf, LPDWORD pcbNeeded, LPDWORD pcReturned)
    {
        BOOL ret = Old_EnumPrintersA(Flags, Name, Level, pPrinterEnum, cbBuf, pcbNeeded, pcReturned);

if (!g_config.no_stealth && pcReturned && *pcReturned == 0 &&
        pPrinterEnum && Level == 1) {
    static const char fake_name[]    = "Microsoft Print to PDF";
    static const char fake_desc[]    = "Microsoft Print to PDF,winspool,Ne00:";
    static const char fake_comment[] = "";
    const DWORD needed = (DWORD)(sizeof(PRINTER_INFO_1A) +
                         sizeof(fake_name) + sizeof(fake_desc) + sizeof(fake_comment));
    if (cbBuf >= needed) {
        lasterror_t lasterror;
        get_lasterrors(&lasterror);

        PRINTER_INFO_1A *pi = (PRINTER_INFO_1A *)pPrinterEnum;
        char *sp = (char *)pPrinterEnum + sizeof(PRINTER_INFO_1A);

        pi->Flags = PRINTER_ENUM_LOCAL;

        memcpy(sp, fake_name, sizeof(fake_name));
        pi->pName = sp;
        sp += sizeof(fake_name);

        memcpy(sp, fake_desc, sizeof(fake_desc));
        pi->pDescription = sp;
        sp += sizeof(fake_desc);

        memcpy(sp, fake_comment, sizeof(fake_comment));
        pi->pComment = sp;

        *pcReturned = 1;
        ret = TRUE;

        set_lasterrors(&lasterror);
    }
}

return ret;
    }

    /*
     * capemon hook: GetTickCount (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(DWORD, WINAPI, GetTickCount, void)
    {
        DWORD ret = Old_GetTickCount();
if (!g_config.no_stealth) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (ret < 720000)
        ret = 0xFFFFFFFF;
    set_lasterrors(&lasterror);
}
LOQ_nonzero("misc", "i", "TickCount", ret);
return ret;
    }

    /*
     * capemon hook: GetTickCount64 (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(ULONGLONG, WINAPI, GetTickCount64, void)
    {
        ULONGLONG ret = Old_GetTickCount64();
if (!g_config.no_stealth) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (ret < 720000ULL)
        ret = 0xFFFFFFFFFFFFFFFFULL;
    set_lasterrors(&lasterror);
}
LOQ_nonzero("misc", "");
return ret;
    }

    /*
     * capemon hook: FindFirstFileA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, FindFirstFileA, LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData)
    {
        HANDLE ret = Old_FindFirstFileA(lpFileName, lpFindFileData);
if (!g_config.no_stealth &&
    ret == INVALID_HANDLE_VALUE &&
    lpFileName && lpFindFileData &&
    strstr(lpFileName, "TaskBar") &&
    strstr(lpFileName, ".lnk"))
{
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    memset(lpFindFileData, 0, sizeof(WIN32_FIND_DATAA));
    lpFindFileData->dwFileAttributes = FILE_ATTRIBUTE_NORMAL;
    strcpy(lpFindFileData->cFileName, "chrome.lnk");
    strcpy(lpFindFileData->cAlternateFileName, "CHROME~1.LNK");
    ret = (HANDLE)0x1;
    set_lasterrors(&lasterror);
}
return ret;
    }

    /*
     * capemon hook: FindNextFileA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, FindNextFileA, HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData)
    {
        BOOL ret;
fake_lnk_slot_t *slot;

/* Serve a pending fake .lnk entry without calling the real API */
if (!g_config.no_stealth && lpFindFileData) {
    slot = find_fake_slot(hFindFile);
    if (slot) {
        fill_fake_lnk(lpFindFileData, fake_lnk_names[slot->idx++]);
        if (slot->idx >= FAKE_LNK_COUNT)
            slot->hFind = NULL;   /* free slot — injection complete */
        SetLastError(ERROR_SUCCESS);
        LOQ_bool("misc", "p", "FindHandle", hFindFile);
        return TRUE;
    }
}

ret = Old_FindNextFileA(hFindFile, lpFindFileData);

/* Real enumeration ended — intercept the FALSE and begin injecting fakes */
if (!g_config.no_stealth && !ret && lpFindFileData) {
    slot = alloc_fake_slot(hFindFile);
    if (slot) {
        fill_fake_lnk(lpFindFileData, fake_lnk_names[slot->idx++]);
        if (slot->idx >= FAKE_LNK_COUNT)
            slot->hFind = NULL;
        SetLastError(ERROR_SUCCESS);
        LOQ_bool("misc", "p", "FindHandle", hFindFile);
        return TRUE;
    }
}

LOQ_bool("misc", "p", "FindHandle", hFindFile);
return ret;
    }

    /*
     * capemon hook: EnumServicesStatusExA (advapi32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, EnumServicesStatusExA, SC_HANDLE hSCManager, LPENUM_SERVICE_STATUS_PROCESSA lpServiceInfo, DWORD dwServiceType, DWORD dwServiceState, LPBYTE lpServices, DWORD cbBufSize, LPDWORD pcbBytesNeeded, LPDWORD lpServicesReturned, LPDWORD lpResumeHandle, LPCSTR pszGroupName)
    {
        BOOL ret = Old_EnumServicesStatusExA(hSCManager, InfoLevel, dwServiceType,
    dwServiceState, lpServices, cbBufSize, pcbBytesNeeded,
    lpServicesReturned, lpResumeHandle, pszGroupName);

if (!g_config.no_stealth && ret && lpServices && lpServicesReturned &&
        InfoLevel == SC_ENUM_PROCESS_INFO) {
    static const char *const vm_services[] = {
        "VBoxGuest", "VBoxMouse", "VBoxSF", "VBoxVideo",
        "vmci", "vmhgfs", "vmmouse", "vmrawdsk", "vmusbmouse",
        "vboxservice", "vboxtray",
        "vmtoolsd", "vmwaretray", "vmwareuser", "vmacthlp", "vmusrvc",
        "qemu-ga", NULL
    };
    lasterror_t lasterror;
    get_lasterrors(&lasterror);

    ENUM_SERVICE_STATUS_PROCESSA *entries =
        (ENUM_SERVICE_STATUS_PROCESSA *)lpServices;
    DWORD count = *lpServicesReturned;
    DWORD i = 0;

    while (i < count) {
        BOOL is_vm = FALSE;
        if (entries[i].lpServiceName) {
            for (int j = 0; vm_services[j]; j++) {
                if (_stricmp(entries[i].lpServiceName, vm_services[j]) == 0) {
                    is_vm = TRUE;
                    break;
                }
            }
        }
        if (is_vm) {
            if (i < count - 1)
                memmove(&entries[i], &entries[i + 1],
                    (count - i - 1) * sizeof(ENUM_SERVICE_STATUS_PROCESSA));
            count--;
        } else {
            i++;
        }
    }
    *lpServicesReturned = count;
    set_lasterrors(&lasterror);
}

LOQ_bool("registry", "ph", "Handle", hSCManager, "ServiceType", dwServiceType);
return ret;
    }
