/*
 * hook_mirage.c — SAGE-generated hook implementations.
 * Auto-regenerated; do not edit by hand.
 */
#include "hooking.h"
#include "log.h"
#include "config.h"
    /*
     * capemon hook: PathFileExistsA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, PathFileExistsA, LPCSTR pszPath)
    {
        BOOL ret = Old_PathFileExistsA(pszPath);
if (!g_config.no_stealth && ret && pszPath) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (strstr(pszPath, "7-Zip") ||
        strstr(pszPath, "WinRAR") ||
        strstr(pszPath, "WinZip") ||
        strstr(pszPath, "peazip") ||
        strstr(pszPath, "PeaZip") ||
        strstr(pszPath, "Bandizip") ||
        strstr(pszPath, "IZArc") ||
        strstr(pszPath, "PowerArchiver")) {
        ret = FALSE;
    }
    set_lasterrors(&lasterror);
}
LOQ_bool("misc", "s", "Path", pszPath);
return ret;
    }

    /*
     * capemon hook: RegQueryInfoKeyA (advapi32.dll.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(LSTATUS, WINAPI, RegQueryInfoKeyA, HKEY hKey, LPSTR lpClass, LPDWORD lpcClass, LPDWORD lpReserved, LPDWORD lpcSubKeys, LPDWORD lpcMaxSubKeyLen, LPDWORD lpcMaxClassLen, LPDWORD lpcValues, LPDWORD lpcMaxValueNameLen, LPDWORD lpcMaxValueLen, LPDWORD lpcbSecurityDescriptor, PFILETIME lpftLastWriteTime)
    {
        LSTATUS ret = Old_RegQueryInfoKeyA(hKey, lpClass, lpcClass, lpReserved,
    lpcSubKeys, lpcMaxSubKeyLen, lpcMaxClassLen, lpcValues,
    lpcMaxValueNameLen, lpcMaxValueLen, lpcbSecurityDescriptor,
    lpftLastWriteTime);

if (!g_config.no_stealth && ret == ERROR_SUCCESS && lpcSubKeys && *lpcSubKeys == 0) {
    typedef NTSTATUS (WINAPI *pfnNtQueryKey)(HANDLE, INT, PVOID, ULONG, PULONG);
    static pfnNtQueryKey _NtQueryKey = NULL;
    if (!_NtQueryKey)
        _NtQueryKey = (pfnNtQueryKey)GetProcAddress(
            GetModuleHandleA("ntdll.dll"), "NtQueryKey");

    if (_NtQueryKey) {
        struct {
            ULONG NameLength;
            WCHAR Name[512];
        } kni;
        ULONG resLen = 0;
        /* KeyNameInformation == 3; path returned as \REGISTRY\USER\<SID>\... */
        if (NT_SUCCESS(_NtQueryKey(hKey, 3, &kni, sizeof(kni), &resLen))) {
            ULONG nameChars = kni.NameLength / sizeof(WCHAR);
            if (nameChars < 512) {
                kni.Name[nameChars] = L'\0';
                if (wcsstr(kni.Name, L"Outlook\\Profiles") != NULL) {
                    lasterror_t lasterror;
                    get_lasterrors(&lasterror);
                    *lpcSubKeys = 1;
                    set_lasterrors(&lasterror);
                }
            }
        }
    }
}

return ret;
    }

    /*
     * capemon hook: CreateToolhelp32Snapshot (kernel32.dll.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(HANDLE, WINAPI, CreateToolhelp32Snapshot, DWORD dwFlags, DWORD th32ProcessID)
    {
        HANDLE ret = Old_CreateToolhelp32Snapshot(dwFlags, th32ProcessID);
LOQ_handle("misc", "hI", "Flags", dwFlags, "ProcessId", th32ProcessID);
return ret;
    }

    /*
     * capemon hook: IsProcessorFeaturePresent (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, IsProcessorFeaturePresent, DWORD ProcessorFeature)
    {
        BOOL ret = Old_IsProcessorFeaturePresent(ProcessorFeature);
if (!g_config.no_stealth) {
    if (ProcessorFeature == PF_VIRT_FIRMWARE_ENABLED) {
        lasterror_t lasterror;
        get_lasterrors(&lasterror);
        ret = FALSE;
        set_lasterrors(&lasterror);
    }
}
LOQ_bool("misc", "h", "ProcessorFeature", ProcessorFeature);
return ret;
    }

    /*
     * capemon hook: GetPwrCapabilities (powrprof.dll.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, GetPwrCapabilities, PSYSTEM_POWER_CAPABILITIES lpspc)
    {
        lasterror_t lasterror;

BOOL ret = Old_GetPwrCapabilities(lpspc);

if (!g_config.no_stealth && ret && lpspc) {
    get_lasterrors(&lasterror);
    lpspc->SystemS1      = TRUE;
    lpspc->SystemS2      = TRUE;
    lpspc->SystemS3      = TRUE;
    lpspc->SystemS4      = TRUE;
    lpspc->ThermalControl = TRUE;
    set_lasterrors(&lasterror);
}

LOQ_bool("misc", "p", "Capabilities", lpspc);
return ret;
    }

    /*
     * capemon hook: EnumPrintersA (winspool.drv.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, EnumPrintersA, DWORD Flags, LPSTR Name, DWORD Level, LPBYTE pPrinterEnum, DWORD cbBuf, LPDWORD pcbNeeded, LPDWORD pcReturned)
    {
        BOOL ret = Old_EnumPrintersA(Flags, Name, Level, pPrinterEnum, cbBuf, pcbNeeded, pcReturned);

if (!g_config.no_stealth && pcReturned && *pcReturned == 0 &&
        pPrinterEnum && Level == 1) {
    static const char fake_name[]    = "Microsoft Print to PDF";
    static const char fake_desc[]    = "Microsoft Print to PDF,winspool,Ne00:";
    static const char fake_comment[] = "";
    const DWORD needed = (DWORD)(sizeof(PRINTER_INFO_1A) +
                         sizeof(fake_name) + sizeof(fake_desc) + sizeof(fake_comment));
    if (cbBuf >= needed) {
        lasterror_t lasterror;
        get_lasterrors(&lasterror);

        PRINTER_INFO_1A *pi = (PRINTER_INFO_1A *)pPrinterEnum;
        char *sp = (char *)pPrinterEnum + sizeof(PRINTER_INFO_1A);

        pi->Flags = PRINTER_ENUM_LOCAL;

        memcpy(sp, fake_name, sizeof(fake_name));
        pi->pName = sp;
        sp += sizeof(fake_name);

        memcpy(sp, fake_desc, sizeof(fake_desc));
        pi->pDescription = sp;
        sp += sizeof(fake_desc);

        memcpy(sp, fake_comment, sizeof(fake_comment));
        pi->pComment = sp;

        *pcReturned = 1;
        ret = TRUE;

        set_lasterrors(&lasterror);
    }
}

return ret;
    }

    /*
     * capemon hook: GetTickCount (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(DWORD, WINAPI, GetTickCount, void)
    {
        DWORD ret = Old_GetTickCount();
if (!g_config.no_stealth) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (ret < 720000)
        ret = 0xFFFFFFFF;
    set_lasterrors(&lasterror);
}
LOQ_nonzero("misc", "i", "TickCount", ret);
return ret;
    }

    /*
     * capemon hook: GetTickCount64 (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(ULONGLONG, WINAPI, GetTickCount64, void)
    {
        ULONGLONG ret = Old_GetTickCount64();
if (!g_config.no_stealth) {
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    if (ret < 720000ULL)
        ret = 0xFFFFFFFFFFFFFFFFULL;
    set_lasterrors(&lasterror);
}
LOQ_nonzero("misc", "");
return ret;
    }

    /*
     * capemon hook: FindFirstFileA (kernel32.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(BOOL, WINAPI, FindFirstFileA, LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData)
    {
        HANDLE ret = Old_FindFirstFileA(lpFileName, lpFindFileData);
if (!g_config.no_stealth &&
    ret == INVALID_HANDLE_VALUE &&
    lpFileName && lpFindFileData &&
    strstr(lpFileName, "TaskBar") &&
    strstr(lpFileName, ".lnk"))
{
    lasterror_t lasterror;
    get_lasterrors(&lasterror);
    memset(lpFindFileData, 0, sizeof(WIN32_FIND_DATAA));
    lpFindFileData->dwFileAttributes = FILE_ATTRIBUTE_NORMAL;
    strcpy(lpFindFileData->cFileName, "chrome.lnk");
    strcpy(lpFindFileData->cAlternateFileName, "CHROME~1.LNK");
    ret = (HANDLE)0x1;
    set_lasterrors(&lasterror);
}
return ret;
    }

    /*
     * capemon hook: GetModuleHandleW (kernel32.dll.dll)
     * Auto-generated by SAGE EvasionCountermeasure — do not edit manually.
     */
    #include "hooking.h"
    #include "log.h"
    #include "config.h"

    HOOKDEF(HMODULE, WINAPI, GetModuleHandleW, LPCWSTR lpModuleName)
    {
        static const wchar_t *const sandbox_modules[] = {
    L"sbiedll.dll", L"snxhk.dll", L"api_log.dll", L"dir_watch.dll",
    L"pstorec.dll", L"vmcheck.dll", L"wpespy.dll", L"cuckoomon.dll",
    L"cmdvrt32.dll", L"cmdvrt64.dll", L"ida.exe", L"x64dbg.exe",
    NULL
};

HMODULE ret = Old_GetModuleHandleW(lpModuleName);

if (!g_config.no_stealth && ret && lpModuleName) {
    lasterror_t lasterror;
    for (int i = 0; sandbox_modules[i]; i++) {
        if (_wcsicmp(lpModuleName, sandbox_modules[i]) == 0) {
            get_lasterrors(&lasterror);
            ret = NULL;
            set_lasterrors(&lasterror);
            break;
        }
    }
}

return ret;
    }
