name: SAGE hooks build

on:
  push:
    branches: ["MIRAGE", "sage-hooks"]
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: capemon.sln

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            platform: Win32
          - arch: x64
            platform: x64

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ matrix.platform }} ${{ env.SOLUTION_FILE_PATH }}

      - name: Upload x86 DLL
        if: matrix.arch == 'x86'
        uses: actions/upload-artifact@v4
        with:
          name: capemon_x86
          path: Release\capemon.dll
          if-no-files-found: error

      - name: Upload x64 DLL
        if: matrix.arch == 'x64'
        uses: actions/upload-artifact@v4
        with:
          name: capemon_x64
          path: x64\Release\capemon_x64.dll
          if-no-files-found: error
